name: ci

on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master

jobs:
  ci:
    name: specs
    runs-on: [actuated-arm64-2cpu-4gb, cncf, btf]
    steps:
      - uses: actions/checkout@v1
      - name: Check ls /sys/kernel/btf/vmlinux
        run: |
          sudo ls /sys/kernel/btf/vmlinux
      - name: Setup tzdata
        run: |
          sudo apt-get update
          sudo apt-get install -y distro-info awscli

